import type { Logger } from '@agentcoders/shared';
import type { AdoClient } from './ado-client.js';
import type { GitClient } from './git-client.js';

export interface CreatePrResult {
  prId: number;
  url: string;
}

export class PrManager {
  constructor(
    private readonly ado: AdoClient,
    private readonly git: GitClient,
    private readonly repositoryId: string,
    private readonly logger: Logger,
  ) {}

  async preFlightCheck(baseBranch = 'main'): Promise<{ fresh: boolean; behindBy: number }> {
    const behindBy = await this.git.getCommitsBehind(baseBranch);
    if (behindBy > 0) {
      this.logger.info({ behindBy }, 'Branch is behind base — attempting rebase');
      const result = await this.git.rebase(baseBranch);
      if (!result.success) {
        return { fresh: false, behindBy };
      }
    }
    return { fresh: true, behindBy: 0 };
  }

  async createPr(params: {
    workItemId: number;
    title: string;
    branch: string;
    description: string;
    baseBranch?: string;
  }): Promise<CreatePrResult> {
    const { workItemId, title, branch, description, baseBranch = 'main' } = params;

    // Push latest
    await this.git.exec(['push', 'origin', branch]);

    const pr = await this.ado.createPullRequest({
      repositoryId: this.repositoryId,
      sourceRefName: `refs/heads/${branch}`,
      targetRefName: `refs/heads/${baseBranch}`,
      title: `[AI] ${title}`,
      description: this.formatPrDescription(workItemId, description),
      workItemIds: [workItemId],
      autoComplete: true,
      squashMerge: true,
      deleteSourceBranch: true,
    });

    // Add comment to work item
    await this.ado.addComment(
      workItemId,
      `PR #${pr.pullRequestId} created by AI agent: ${pr.url}`,
    );

    this.logger.info({ prId: pr.pullRequestId, workItemId }, 'Created pull request');
    return { prId: pr.pullRequestId, url: pr.url };
  }

  private formatPrDescription(workItemId: number, description: string): string {
    return [
      `## AI-Generated Pull Request`,
      ``,
      `**Work Item:** #${workItemId}`,
      ``,
      `### Changes`,
      description,
      ``,
      `---`,
      `*This PR was generated by an AgentCoders AI agent. Please review carefully.*`,
    ].join('\n');
  }
}
